name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag registry.cn-beijing.aliyuncs.com/sf-service/zeek-kafka:latest
    - name: Login Ali
      run: docker login --username=北京数风科技有限公司 --password=${{ env.ALIDOCKERPWD }} registry.cn-beijing.aliyuncs.com
    - name: Push
      run: docker push registry.cn-beijing.aliyuncs.com/sf-service/zeek-kafka:latest
